spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: mail
    password: mail
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 34v2b323uhu23728487824982392neuyg7g4763237dsdsd23jhj2j2
      expiration: 8640000

  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account

  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088